// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {engine} from '../models';
import {bot} from '../models';

export function ApplyBestMove(arg1:number,arg2:number):Promise<desktop.TurnResponse>;

export function ApplyDice(arg1:number,arg2:number,arg3:number):Promise<desktop.TurnResponse>;

export function BackgroundTrainingStatus():Promise<desktop.BackgroundTrainingResponse>;

export function Close():Promise<void>;

export function Export(arg1:string):Promise<void>;

export function ImportMoveLog(arg1:string):Promise<desktop.ImportLogResponse>;

export function LegalLines(arg1:number,arg2:number):Promise<Array<engine.TurnLine>>;

export function SelfLearn(arg1:number):Promise<desktop.SelfLearnResponse>;

export function StartBackgroundTraining():Promise<desktop.BackgroundTrainingResponse>;

export function StartGame(arg1:desktop.StartRequest):Promise<desktop.TurnResponse>;

export function State():Promise<desktop.TurnResponse>;

export function StopBackgroundTraining():Promise<desktop.BackgroundTrainingResponse>;

export function SuggestMove(arg1:number,arg2:number):Promise<bot.Decision>;

export function Undo():Promise<desktop.TurnResponse>;
