// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyBestMove(arg1, arg2) {
  return window['go']['desktop']['API']['ApplyBestMove'](arg1, arg2);
}

export function ApplyDice(arg1, arg2, arg3) {
  return window['go']['desktop']['API']['ApplyDice'](arg1, arg2, arg3);
}

export function BackgroundTrainingStatus() {
  return window['go']['desktop']['API']['BackgroundTrainingStatus']();
}

export function Close() {
  return window['go']['desktop']['API']['Close']();
}

export function Export(arg1) {
  return window['go']['desktop']['API']['Export'](arg1);
}

export function ImportMoveLog(arg1) {
  return window['go']['desktop']['API']['ImportMoveLog'](arg1);
}

export function LegalLines(arg1, arg2) {
  return window['go']['desktop']['API']['LegalLines'](arg1, arg2);
}

export function SelfLearn(arg1) {
  return window['go']['desktop']['API']['SelfLearn'](arg1);
}

export function StartBackgroundTraining() {
  return window['go']['desktop']['API']['StartBackgroundTraining']();
}

export function StartGame(arg1) {
  return window['go']['desktop']['API']['StartGame'](arg1);
}

export function State() {
  return window['go']['desktop']['API']['State']();
}

export function StopBackgroundTraining() {
  return window['go']['desktop']['API']['StopBackgroundTraining']();
}

export function SuggestMove(arg1, arg2) {
  return window['go']['desktop']['API']['SuggestMove'](arg1, arg2);
}

export function SwapBotSide() {
  return window['go']['desktop']['API']['SwapBotSide']();
}

export function Undo() {
  return window['go']['desktop']['API']['Undo']();
}
