// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {engine} from '../models';

export function ApplyDice(arg1:number,arg2:number,arg3:number):Promise<desktop.TurnResponse>;

export function Close():Promise<void>;

export function Export(arg1:string):Promise<void>;

export function LegalLines(arg1:number,arg2:number):Promise<Array<engine.TurnLine>>;

export function StartGame(arg1:desktop.StartRequest):Promise<desktop.TurnResponse>;

export function State():Promise<desktop.TurnResponse>;

export function Undo():Promise<desktop.TurnResponse>;
