// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyDice(arg1, arg2, arg3) {
  return window['go']['desktop']['API']['ApplyDice'](arg1, arg2, arg3);
}

export function Close() {
  return window['go']['desktop']['API']['Close']();
}

export function Export(arg1) {
  return window['go']['desktop']['API']['Export'](arg1);
}

export function LegalLines(arg1, arg2) {
  return window['go']['desktop']['API']['LegalLines'](arg1, arg2);
}

export function StartGame(arg1) {
  return window['go']['desktop']['API']['StartGame'](arg1);
}

export function State() {
  return window['go']['desktop']['API']['State']();
}

export function Undo() {
  return window['go']['desktop']['API']['Undo']();
}
